<?php

namespace AppBundle\Repository\Default;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
		public function findByEventId($id){
		echo ("oui");
		return;
	}
}
