<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	/**
	 * Fonction permettant de chercher le username
	 */
	public function findByUsername($username) 
	{
		$query = $this->createQueryBuilder('u')
		    ->WHERE('u.username = :username')
		     ->setParameter('username', $username)
		    ->getQuery();

		return $query->getResult();
	}

	/**
	 * Fonction permettant de chercher le username
	 */
	public function findByUserId($userid) 
	{
		$query = $this->createQueryBuilder('u')
		    ->WHERE('u.userId = :userid')
		     ->setParameter('userid', $userid)
		    ->getQuery();

		return $query->getResult();
	}

	/**
	 * Fonction permettant de chercher le token d'un utilisateur
	 */

	public function findByToken($token) 
	{
		$query = $this->createQueryBuilder('u')
		    ->WHERE('u.token = :token')
		     ->setParameter('token', $token)
		    ->getQuery();

		return $query->getResult();
	}
}


