<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByUsername($username) 
	{
		$query = $this->createQueryBuilder('u')
		    ->WHERE('u.userName = :username')
		     ->setParameter('username', $username)
		    ->getQuery();

		return $query->getResult();
	}
}


