security:
    encoders:
        Theatre\AdministrateurBundle\Entity\User: plaintext
        #THEATRE\AuthentificationBundle\Security\WebserviceUser: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      in_memory:
            memory: ~

      api_key_user_provider:
            id: AppBundle\Security\ApiKeyUserProvider

             #webservice:
           # id: THEATRE\AuthentificationBundle\Security\WebServiceUserProvider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/theatre
            stateless: false
            simple_preauth:
                authenticator: AppBundle\Security\ApiKeyAuthenticator
            provider: api_key_user_provider
            #logout_on_user_change: true
            
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: 
             #  login_path: theatre_authentification_registration
              # check_path: theatre_authentification_registration
                
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/theatre, roles: [ROLE_USER, ROLE_ADMIN]}
        - { path: ^/admin, roles: ROLE_ADMIN }
    # access_control:
     # - { path: ^/authentification/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
     #   - { path: ^/, roles: ROLE_USER }
            
