theatre_administrateur_homepage:
    path:     /admin
    defaults: { _controller: TheatreAdministrateurBundle:Default:index }
theatre_administrateur_create:
    path:     /admin/create
    defaults: { _controller: TheatreAdministrateurBundle:Default:createEvent }
theatre_administrateur_edit:
    path:     /admin/edit/{id}
    defaults: { _controller: TheatreAdministrateurBundle:Default:edit }
    requirements:
      id: '\d+'
theatre_administrateur_delete:
    path:     /admin/delete/{id}
    defaults: { _controller: TheatreAdministrateurBundle:Default:delete}
    requirements:
      id: '\d+'
theatre_homepageUser:
    path:     /user/{id}
    defaults: { _controller: TheatreAdministrateurBundle:Default:indexUser }
    requirements:
      id: '\d+'
theatre_homepageAdmin:
    path:     /admin
    defaults: { _controller: TheatreAdministrateurBundle:Default:indexAdmin }
theatre_utilisateur_edit:
    path:     /editu/{id}
    defaults: { _controller: TheatreAdministrateurBundle:Default:editUser }
    requirements:
      id: '\d+'
theatre_event_list:
    path: /listevent
    defaults: { _controller: TheatreAdministrateurBundle:Default:listEvent }
theatre_participate_event:
    path: /participate
    defaults: { _controller: TheatreAdministrateurBundle:Default:participateEvent}
theatre_test:
    path:     /test
    defaults: { _controller: TheatreAdministrateurBundle:Default:test }
